title: Efficient Scientific Computing @ SESAME 2026
menu_header: ESC@SESAME26
indico: https://indico.sesame.org.jo/event/13/

# the jekylly-github-metadata plugin generates the site.github context
# and uses it to populate variables such as site.url and site.base_url
plugins:
  - "jekyll-github-metadata"
  
highlighter: rouge
baseurl: /sesame26
exercises_repo: https://github.com/infn-esc/sesame26/blob/main

menu:
  - name: basic
    items:
    - name: environment
    - name: compiling
    - name: makefile
  - name: memory
    label: Memory Management
    items:
    - name: basics
    - name: datastructure
      label: Data structures
    - name: fs
      label: False Sharing 
    - name: asan
      label: Address Sanitizer
#   - name: architecture
#     items:
#     - name: discoverHW
#       label: Discover Hardware Architecture
#     - name: perf
#       label: Profiling using "perf"
  - name: cpp
    label: C++
    items:
    - name: containers
    - name: algorithms
    - name: move_ops
      label: Move operations
#   - name: parallelism
#     label: PARALLELISM
#     items:
#     - name: parcpp
#       label: Parallel C++
#     - name: cuda
#       label: CUDA
  - name: mpi
    label: MPI
    items:
       - name: MPIusage
         label: Launching MPI Programs
  - name: pybind
    label: Python bindings
    items:
    - name: cpp_to_py
      label: Using C++ in Python
    - name: py_to_cpp
      label: Using Python in C++


# defaults:
#   -
#     scope:
#       path: "basic/"
#       type: "posts"
#     values:
#       category: "basic"
#       layout: "main"
